### ISSUE TITLE
Error running ros commands

### ISSUE THREAD

**Issue by Rezenders** [ros-melodic-arch/ros-melodic-ros-core#1]
I'm following the [installation instructions](https://wiki.ros.org/melodic/Installation/ArchLinux) and I get the following error:

    $ rosdep init
    Traceback (most recent call last):
      File "/usr/bin/rosdep", line 3, in <module>
        from rosdep2.main import rosdep_main
      File "/usr/lib/python3.8/site-packages/rosdep2/__init__.py", line 40, in <module>
        from .installers import InstallerContext, Installer, \
      File "/usr/lib/python3.8/site-packages/rosdep2/installers.py", line 36, in <module>
        from rospkg.os_detect import OsDetect
      File "/usr/lib/python3.8/site-packages/rospkg/os_detect.py", line 42, in <module>
        import distro
    ModuleNotFoundError: No module named 'distro'

I did source /opt/melodic/setup.bash. A similar error occurs when I run roscore:
    
    $ roscore
    Traceback (most recent call last):
      File "/opt/ros/melodic/bin/roscore", line 72, in <module>
        import roslaunch
      File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/__init__.py", line 62, in <module>
        from .scriptapi import ROSLaunch
      File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/scriptapi.py", line 42, in <module>
        import roslaunch.parent
      File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/parent.py", line 54, in <module>
        import roslaunch.server
      File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/server.py", line 79, in <module>
        from rosgraph_msgs.msg import Log
      File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/__init__.py", line 2, in <module>
        from ._Log import *
      File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/_Log.py", line 8, in <module>
        import std_msgs.msg
    ModuleNotFoundError: No module named 'std_msgs'

I am guessing this error is somehow related to python,  it seems to me that it is trying to use python3 deps. When I install ROS from the AUR packages does  it install ROS for python2? Maybe it does not install the dependencies required for python3? Is it possible to force it to use python2?

**Comment by acxz** [comment]
Do you remember what options you choose during the `yay` install? If I remember correctly at one point you are prompted to choose between `ros-build-tools` and `ros-build-tools-py3`. I have always choose `ros-build-tools-py3` and have never seen this error.

Besides giving a more detailed account of your installation. Try to do a clean rebuild of all your ros packages.

**Comment by Rezenders** [comment]
At first I used pikaur as helper, and it did not ask me to choose anything. So I removed everything and installed again using yay. I tried installing just `ros-melodic-ros-base`, and then also `ros-melodic-desktop`.

When using yay it was not aked if I wanted to use `ros-build-tools `or r`os-build-tools-py3`, only the following options were presented:

```
:: There are 2 providers available for ros-melodic-roscpp:    
:: Repository AUR    
    1) ros-melodic-roscpp 2) ros-melodic-roscpp-git     
    
Enter a number (default=1): 2    
:: There are 2 providers available for ros-melodic-message-filters:    
:: Repository AUR    
    1) ros-melodic-message-filters 2) ros-melodic-message-filters-git     
    
Enter a number (default=1): 2    
:: There are 2 providers available for python-crypto:    
:: Repository community    
    1) python-pycryptodome     
:: Repository arch4edu    
    2) python-pycrypto     
    
Enter a number (default=1): 2    
:: Checking for conflicts...    
:: Checking for inner conflicts...    
    
==> Inner conflicts found:    
 -> ros-build-tools-py3: ros-build-tools    
    
==> Conflicting packages will have to be confirmed manually
```

I tried all cominations of options, but it did not work. I see that there is a message indicating conflicts between `ros-build-tools-py3` and `ros-build-tools` but I dont know how to solve it.

**Comment by acxz** [comment]
Can you make sure to remove all ROS related packages on your system? You can do so with the following: ‘yay -Rns $(yay -Qsq ros-melodic)’ Also make sure to remove ros-build-tools: ‘yay -Rns ros-build-tools’.

After that try to install ros-melodic-ros-base with a clean build. when yay asks you to clean build press ‘A’.

The only AUR helper we test against (and thereby support) is ‘yay’. Please refrain from using pikaur.

**Comment by Rezenders** [comment]
I did what you recommended, erasing everything.

But when I ran:
```
yay -S ros-melodic-ros-base
```
I got the following error:
```
error: could not set install reason for package ros-build-tools (could not find or read package)exit status 1
```

After this I checked and ros-build-tools-py3 was installed.

Then, I tried installing again with :
```
yay -S ros-melodic-ros-base
```
The installation completed but I am still getting the error:

```
$ roscore
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/roscore", line 72, in <module>
    import roslaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/__init__.py", line 62, in <module>
    from .scriptapi import ROSLaunch
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/scriptapi.py", line 42, in <module>
    import roslaunch.parent
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/parent.py", line 54, in <module>
    import roslaunch.server
  File "/opt/ros/melodic/lib/python3.8/site-packages/roslaunch/server.py", line 79, in <module>
    from rosgraph_msgs.msg import Log
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/__init__.py", line 2, in <module>
    from ._Log import *
  File "/opt/ros/melodic/lib/python3.8/site-packages/rosgraph_msgs/msg/_Log.py", line 8, in <module>
    import std_msgs.msg
ModuleNotFoundError: No module named 'std_msgs'

```

**Comment by acxz** [comment]
Can you try `yay -Syu ros-build-tools-py3`? And show me the output of that?

The first error you are getting is something I haven't seen before, I feel like we should tackle that.

**Comment by Rezenders** [comment]
```
yay -Syu ros-build-tools-py3
:: Synchronizing package databases...
 core is up to date
 extra                                               1642,4 KiB  2,23 MiB/s 00:01 [###############################################] 100%
 community                                              4,8 MiB  4,44 MiB/s 00:01 [###############################################] 100%
 arch4edu is up to date
warning: ros-build-tools-py3-0.3.1-3 is up to date -- reinstalling
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (15) clutter-1.26.4-1  cogl-1.22.6-1  geocode-glib-3.26.2-1  gnome-bluetooth-3.34.1-1  gnome-boxes-3.36.0-1
              gnome-settings-daemon-3.36.0-1  gsettings-desktop-schemas-3.36.0-1  libgweather-3.36.0-1  libluv-1.34.2-1
              libvirt-glib-3.0.0-1  python-pycparser-2.20-1  python-pygments-2.6.1-2  tracker-2.3.4-1  tracker-miners-2.3.3-1
              ros-build-tools-py3-0.3.1-3

Total Download Size:   12,30 MiB
Total Installed Size:  84,27 MiB
Net Upgrade Size:       3,32 MiB

:: Proceed with installation? [Y/n] y

```

Then everything proceeds to install

**Comment by acxz** [comment]
Sweet, okay lets go ahead and remove `ros-build-tools-py3` and all of ros:
`yay -Rns $(yay -Qsq ros-melodic)` `yay -Rns ros-build-tools` `yay -Rns ros-build-tools-py3`

Just to confirm can you post the output of `yay -Qsq ros` after this command?

**Comment by acxz** [comment]
Also one more thing can you run the following command: `rm -rf ~/.cache/yay/ros-*`
and post the output of `ls ~/.cache/yay/`.

**Comment by Rezenders** [comment]
Ok.

```
$ yay -Qsq ros
cmake
dav1d
electron
electron4
gobject-introspection
gobject-introspection-runtime
kaccounts-integration
krb5
kservice
libao
libmatroska
libmspub
libvncserver
libwmf
libwps
openal
portaudio
pptpclient
python-pytz
qt5-base
```
```
$rm -rf ~/.cache/yay/ros-*
authy     chromium-widevine  pikaur                     python-rosdep     python-rospkg             spotify
autojump  completion.cache   pulseaudio-modules-bt-git  python-rosdistro  skypeforlinux-stable-bin  vcs.json
```
Then I went ahead and also deleted `python-rosdep`, `python-rosdistro` and `python-rospkg`

**Comment by acxz** [comment]
Sweet okay. Now let us run the following command:
`yay -Syu ros-melodic-roslaunch |& tee roslaunch-install-output.txt`

Make sure to use `ros-build-tools-py3`, when prompted.

This will post the output of the install command to a file. Can you post the contents of the file here as well?

**Comment by Rezenders** [comment]
The output is:

<details>
  <summary>output</summary>

  ```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 arch4edu is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> python2-levenshtein: local (0.12.0-5) is newer than AUR (0.12.0-1)
 -> Flagged Out Of Date AUR Packages:  spotify
:: There are 2 providers available for ros-melodic-roscpp:
:: Repository AUR
    1) ros-melodic-roscpp 2) ros-melodic-roscpp-git 

Enter a number (default=1): :: Checking for conflicts...
:: Checking for inner conflicts...

==> Inner conflicts found:
 -> ros-build-tools-py3: ros-build-tools

==> Conflicting packages will have to be confirmed manually

[Repo: 21]  boost-1.72.0-1  console-bridge-0.4.4-1  ros-melodic-cpp-common-0.6.13-3  ros-melodic-rostime-0.6.13-3  ros-melodic-roscpp-traits-0.6.13-2  python-nose-1.3.7-6  gtest-1.8.1-3  python-argparse-1.4.0-7  python-docutils-0.14-4  python-catkin_pkg-0.4.16-1  python-empy-3.3.4-3  gmock-1.8.1-3  ros-build-tools-py3-0.3.1-3  ros-melodic-catkin-0.8.1-1  ros-melodic-genmsg-0.5.12-2  ros-melodic-genpy-0.6.8-2  ros-melodic-roscpp-serialization-0.6.13-2  ros-melodic-message-runtime-0.4.12-2  ros-melodic-std-msgs-0.5.12-1  log4cxx-0.10.0-5  python-netifaces-0.10.9-3
[Repo Make: 7]  ros-build-tools-0.2.0-1  ros-melodic-geneus-2.2.6-2  ros-melodic-gencpp-0.6.2-2  ros-melodic-gennodejs-2.0.1-2  ros-melodic-genlisp-0.4.17-2  ros-melodic-message-generation-0.4.0-2  tinyxml2-7.1.0-1
[Aur: 11]  ros-melodic-rosgraph-msgs-1.11.2-2  ros-melodic-xmlrpcpp-1.14.3-2  ros-melodic-rosbuild-1.14.6-1  ros-melodic-rosconsole-1.13.10-2  ros-melodic-roscpp-1.14.3-2  ros-melodic-rosout-1.14.3-2  ros-melodic-rosgraph-1.14.3-2  ros-melodic-rosparam-1.14.3-1  ros-melodic-rosclean-1.14.6-1  ros-melodic-rosmaster-1.14.3-1  ros-melodic-roslaunch-1.14.3-1
[Aur Make: 9]  ros-melodic-ros-environment-1.2.1-3  python-rospkg-1.2.3-1  python-rosdistro-0.8.0-1  python-rosdep-0.18.0-1  ros-melodic-cmake-modules-0.4.2-1  ros-melodic-rospack-2.5.4-2  ros-melodic-roslib-1.14.6-2  ros-melodic-rosunit-1.14.6-1  ros-melodic-roslang-1.14.6-1

==> Remove make dependencies after install? [y/N] :: Downloaded PKGBUILD (1/20): ros-melodic-rosbuild
:: Downloaded PKGBUILD (2/20): ros-melodic-rosout
:: Downloaded PKGBUILD (3/20): ros-melodic-rosclean
:: Downloaded PKGBUILD (4/20): ros-melodic-roslib
:: Downloaded PKGBUILD (5/20): ros-melodic-ros-environment
:: Downloaded PKGBUILD (6/20): ros-melodic-rosgraph-msgs
:: Downloaded PKGBUILD (7/20): ros-melodic-roslaunch
:: Downloaded PKGBUILD (8/20): ros-melodic-xmlrpcpp
:: Downloaded PKGBUILD (9/20): ros-melodic-roslang
:: Downloaded PKGBUILD (10/20): ros-melodic-rosunit
:: Downloaded PKGBUILD (11/20): ros-melodic-rosgraph
:: Downloaded PKGBUILD (12/20): ros-melodic-cmake-modules
:: Downloaded PKGBUILD (13/20): python-rospkg
:: Downloaded PKGBUILD (14/20): ros-melodic-rosparam
:: Downloaded PKGBUILD (15/20): ros-melodic-rospack
:: Downloaded PKGBUILD (16/20): ros-melodic-rosmaster
:: Downloaded PKGBUILD (17/20): python-rosdep
:: Downloaded PKGBUILD (18/20): python-rosdistro
:: Downloaded PKGBUILD (19/20): ros-melodic-roscpp
:: Downloaded PKGBUILD (20/20): ros-melodic-rosconsole
 20 ros-melodic-rosgraph-msgs                (Build Files Exist)
 19 ros-melodic-xmlrpcpp                     (Build Files Exist)
 18 ros-melodic-rosbuild                     (Build Files Exist)
 17 ros-melodic-ros-environment              (Build Files Exist)
 16 python-rospkg                            (Build Files Exist)
 15 python-rosdistro                         (Build Files Exist)
 14 python-rosdep                            (Build Files Exist)
 13 ros-melodic-cmake-modules                (Build Files Exist)
 12 ros-melodic-rospack                      (Build Files Exist)
 11 ros-melodic-roslib                       (Build Files Exist)
 10 ros-melodic-rosunit                      (Build Files Exist)
  9 ros-melodic-rosconsole                   (Build Files Exist)
  8 ros-melodic-roslang                      (Build Files Exist)
  7 ros-melodic-roscpp                       (Build Files Exist)
  6 ros-melodic-rosout                       (Build Files Exist)
  5 ros-melodic-rosgraph                     (Build Files Exist)
  4 ros-melodic-rosparam                     (Build Files Exist)
  3 ros-melodic-rosclean                     (Build Files Exist)
  2 ros-melodic-rosmaster                    (Build Files Exist)
  1 ros-melodic-roslaunch                    (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> :: Parsing SRCINFO (1/20): ros-melodic-rosgraph-msgs
:: Parsing SRCINFO (2/20): ros-melodic-xmlrpcpp
:: Parsing SRCINFO (3/20): ros-melodic-rosbuild
:: Parsing SRCINFO (4/20): ros-melodic-ros-environment
:: Parsing SRCINFO (5/20): python-rospkg
:: Parsing SRCINFO (6/20): python-rosdistro
:: Parsing SRCINFO (7/20): python-rosdep
:: Parsing SRCINFO (8/20): ros-melodic-cmake-modules
:: Parsing SRCINFO (9/20): ros-melodic-rospack
:: Parsing SRCINFO (10/20): ros-melodic-roslib
:: Parsing SRCINFO (11/20): ros-melodic-rosunit
:: Parsing SRCINFO (12/20): ros-melodic-rosconsole
:: Parsing SRCINFO (13/20): ros-melodic-roslang
:: Parsing SRCINFO (14/20): ros-melodic-roscpp
:: Parsing SRCINFO (15/20): ros-melodic-rosout
:: Parsing SRCINFO (16/20): ros-melodic-rosgraph
:: Parsing SRCINFO (17/20): ros-melodic-rosparam
:: Parsing SRCINFO (18/20): ros-melodic-rosclean
:: Parsing SRCINFO (19/20): ros-melodic-rosmaster
:: Parsing SRCINFO (20/20): ros-melodic-roslaunch
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 arch4edu is up to date
resolving dependencies...
looking for conflicting packages...
warning: removing 'ros-build-tools' from target list because it conflicts with 'ros-build-tools-py3'

Packages (27) boost-1.72.0-1  console-bridge-0.4.4-1  gmock-1.8.1-3  gtest-1.8.1-3  log4cxx-0.10.0-5  python-argparse-1.4.0-7  python-catkin_pkg-0.4.16-1  python-docutils-0.14-4  python-empy-3.3.4-3  python-netifaces-0.10.9-3  python-nose-1.3.7-6  ros-build-tools-py3-0.3.1-3  ros-melodic-catkin-0.8.1-1  ros-melodic-cpp-common-0.6.13-3  ros-melodic-gencpp-0.6.2-2  ros-melodic-geneus-2.2.6-2  ros-melodic-genlisp-0.4.17-2  ros-melodic-genmsg-0.5.12-2  ros-melodic-gennodejs-2.0.1-2  ros-melodic-genpy-0.6.8-2  ros-melodic-message-generation-0.4.0-2  ros-melodic-message-runtime-0.4.12-2  ros-melodic-roscpp-serialization-0.6.13-2  ros-melodic-roscpp-traits-0.6.13-2  ros-melodic-rostime-0.6.13-3  ros-melodic-std-msgs-0.5.12-1  tinyxml2-7.1.0-1

Total Installed Size:  190,18 MiB

:: Proceed with installation? [Y/n] checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing boost...
Optional dependencies for boost
    python: for python bindings [installed]
    python2: for python2 bindings [installed]
installing console-bridge...
installing ros-melodic-cpp-common...
installing ros-melodic-rostime...
installing ros-melodic-roscpp-traits...
installing python-nose...
installing gtest...
installing python-argparse...
installing python-docutils...
installing python-catkin_pkg...
installing python-empy...
installing gmock...
installing ros-build-tools-py3...
Optional dependencies for ros-build-tools-py3
    python3 [installed]
    python-argparse [installed]
    python-yaml [installed]
    python-termcolor
    python-certifi
installing ros-melodic-catkin...
installing ros-melodic-genmsg...
installing ros-melodic-genpy...
installing ros-melodic-roscpp-serialization...
installing ros-melodic-message-runtime...
installing ros-melodic-std-msgs...
installing ros-melodic-geneus...
installing ros-melodic-gencpp...
installing ros-melodic-gennodejs...
installing ros-melodic-genlisp...
installing ros-melodic-message-generation...
installing log4cxx...
installing tinyxml2...
installing python-netifaces...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
error: could not set install reason for package ros-build-tools (could not find or read package)exit status 1

  ```
</details>

**Comment by acxz** [comment]
hmm okay let's try one more thing. Can you comment out the arch4edu repository wherever you added it? I think it should be in pacman.conf?

And then let us repeat the entire pipeline again: remove all ros related packages, remove the build caches in the yay folder and then run `yay -Syu ros-melodic-roslaunch |& tee roslaunch-install-output.txt`.

**Comment by Rezenders** [comment]
When I remove arch4edu I get asked if I want ros-build-tools or ros-build-tools-py3, but I get the following error:

[roslaunch-install-output.txt](https://github.com/ros-melodic-arch/ros-melodic-ros-core/files/4312399/roslaunch-install-output.txt)

**Comment by acxz** [comment]
hmmm. It seems like not using `arch4edu` helped. Okay okay we are moving along.

Do you have any `pip` packages globally installed? Maybe a pip installed package is causing these issues. Please remove all global python packages you installed with `pip`. The package `lostfiles` can help you with this.

After installing the package (`yay -Syu lostfiles`) please show the output of the following command: `sudo lostfiles | grep "/usr/lib/python3.8"`.

**Comment by acxz** [comment]
Also try once more thing. Run a `yay -Syyu` to force sync and refresh with your repositories.

**Comment by acxz** [comment]
@Rezenders Just a reminder that we will be closing this issue in 2 days (7 days after the last user response). Feel free to continue asking for help.

**Comment by bionade24** [comment]
@Rezenders Try to use my Repo. https://wiki.archlinux.org/index.php/Unofficial_user_repositories#oscloud

**Comment by acxz** [comment]
Closing this issue since, @Rezenders is unresponsive
